fix(syndesis): Fix broken --cluster option (#3323)

diff --git a/tools/bin/install-syndesis b/tools/bin/install-syndesis
--- a/tools/bin/install-syndesis
+++ b/tools/bin/install-syndesis
@@ -114,11 +114,15 @@ check_error() {
 }
 
 print_error() {
+    local exit_code=$?
     local error_file="${1:-}"
+    if [ -f $error_file ] && grep -q "ERROR" $error_file; then
+        cat $error_file
+    elif [ $exit_code -ne 0 ]; then
+        echo "ERROR: Last command exited with $exit_code"
+    fi
+
     if [ -f $error_file ]; then
-        if grep -q "ERROR" $error_file; then
-            cat $error_file
-        fi
         rm $error_file
     fi
 }
@@ -149,6 +153,10 @@ add_user_permissions_for_operator() {
         echo "ERROR: No user provided to fix permissions for"
         return
     fi
+
+    # Don't fail on error for a moment, as grep exits with 1 if nothing is found.
+    set +e
+
     local extra_role_installed="$(oc get role -o name | grep syndesis-extra-permissions | wc -l | xargs)"
     local kind="Role"
     local oc_command="policy add-role-to-user --role-namespace=$(oc project -q)"
@@ -158,7 +166,6 @@ add_user_permissions_for_operator() {
         oc_command="adm policy add-cluster-role-to-user"
     fi
 
-    set +e
     if [ $extra_role_installed -eq 0 ]; then
         oc create -f - >/dev/null 2>&1 <<EOT
 ---
