chore(install): Update syndesis-install standalone script

diff --git a/tools/bin/install-syndesis b/tools/bin/install-syndesis
--- a/tools/bin/install-syndesis
+++ b/tools/bin/install-syndesis
@@ -7,9 +7,19 @@
 # have the choice, try to use "syndesis install" as
 # it has more features
 
+# Minimal version for OC
+OC_MIN_VERSION=3.9.0
+
+# Exit if any error occurs
+# Fail on a single failed command in a pipeline (if supported)
 set -o pipefail
+
+# Fail on error and undefined vars (please don't use global vars, but evaluation of functions for return values)
 set -eu
-ARGS="$@"
+
+# Save global script args
+ARGS=("$@")
+
 
 display_usage() {
   cat <<EOT
@@ -19,17 +29,24 @@ Usage: syndesis-install --route <hostname> --console <console-url> [options]
 
 with options:
 
--r --route <host>            The route to install or "auto" to generate a default route based on OpenShift configuration (mandatory)
-   --console <console-url>   The URL to the openshift console
--t --tag <tag>               Optional version to use for the installaton ("latest" by default)
--p --project <project>       Install into this project. The project will be deleted
-                             if it already exists. By default, install into the current project (without deleting)
--w --watch                   Wait until the installation has completed
--o --open                    Open Syndesis after installation (implies --watch)
-   --help                    This help message
--v --verbose                 Verbose logging
+-s  --setup-as-admin          Install CRDs clusterwide. Use --prepare-for-user if you want a specific user to be
+                              able to install Syndesis. You have to run this option once as cluster admin.
+-u  --prepare-for-user <user> Add permissions for the given user so that user can install the operator
+                              in her projects
+    --route                   Route to use. If not given, the route is trying to be detected from the currently
+                              connected cluster.
+   --console <console-url>    The URL to the openshift console
+-t --tag <tag>                Optional version to use for the installaton ("latest" by default)
+   --force                    Override an existing "Syndesis" if present
 
-This tool is for a standalone installation and can be by downloading it from
+-p --project <project>        Install into this project. The project will be deleted
+                              if it already exists. By default, install into the current project (without deleting)
+-w --watch                    Wait until the installation has completed
+-o --open                     Open Syndesis after installation (implies --watch)
+   --help                     This help message
+-v --verbose                  Verbose logging
+
+This tool is for a standalone installation and can be used by downloading it from
 https://raw.githubusercontent.com/syndesisio/syndesis/master/tools/bin/install-syndesis
 (short: https://bit.ly/syndesis-install)
 EOT
@@ -37,6 +54,139 @@ EOT
 
 # ============================================================
 # Helper functions taken over from "syndesis" CLI:
+
+# Checks if a flag is present in the arguments.
+hasflag() {
+    filters="$@"
+    for var in "${ARGS[@]}"; do
+        for filter in $filters; do
+          if [ "$var" = "$filter" ]; then
+              echo 'true'
+              return
+          fi
+        done
+    done
+}
+
+# Read the value of an option.
+readopt() {
+    filters="$@"
+    next=false
+    for var in "${ARGS[@]}"; do
+        if $next; then
+            echo $var
+            break;
+        fi
+        for filter in $filters; do
+            if [[ "$var" = ${filter}* ]]; then
+                local value="${var//${filter}=/}"
+                if [ "$value" != "$var" ]; then
+                    echo $value
+                    return
+                fi
+                next=true
+            fi
+        done
+    done
+}
+
+
+check_error() {
+    local msg="$*"
+    if [ "${msg//ERROR/}" != "${msg}" ]; then
+        if [ -n "${ERROR_FILE:-}" ] && [ -f "$ERROR_FILE" ] && ! grep "$msg" $ERROR_FILE ; then
+            local tmp=$(mktemp /tmp/error-XXXX)
+            echo ${msg} >> $tmp
+            if [ $(wc -c <$ERROR_FILE) -ne 0 ]; then
+              echo >> $tmp
+              echo "===============================================================" >> $tmp
+              echo >> $tmp
+              cat $ERROR_FILE >> $tmp
+            fi
+            mv $tmp $ERROR_FILE
+        fi
+        exit 0
+    fi
+}
+
+print_error() {
+    local error_file="${1:-}"
+    if [ -f $error_file ]; then
+        if grep -q "ERROR" $error_file; then
+            cat $error_file
+        fi
+        rm $error_file
+    fi
+}
+
+# Install the Syndesis custom resource definition
+install_syndesis_crd() {
+    set +e
+    oc get crd >/dev/null 2>&1
+    local err=$?
+    set -e
+    if [ $err -ne 0 ]; then
+        echo "ERROR: Cannot install CRD 'Syndesis'. You have to be a cluster admin to do this."
+        return
+    fi
+
+    local crd_installed=$(oc get crd -o name | grep syndesises.syndesis.io)
+    if [ -z "$crd_installed" ]; then
+        local result=$(create_openshift_resource "install/operator/deploy/syndesis-crd.yml")
+        check_error $result
+    fi
+}
+
+# Fix up some extra permissions required for a regular minishift user
+# Must be run when root
+add_user_permissions_for_operator() {
+    local user="$1"
+    if [ -z "$user" ]; then
+        echo "ERROR: No user provided to fix permissions for"
+        return
+    fi
+    local extra_role_installed=$(oc get role -o name | grep syndesis-extra-permissions)
+    set +e
+    if [ -z "$extra_role_installed" ]; then
+        oc create -f - >/dev/null 2>&1 <<EOT
+---
+kind: Role
+apiVersion: rbac.authorization.k8s.io/v1beta1
+metadata:
+  name: syndesis-extra-permissions
+  labels:
+    app: syndesis
+    syndesis.io/app: syndesis
+    syndesis.io/type: operator
+    syndesis.io/component: syndesis-operator
+rules:
+- apiGroups:
+  - syndesis.io
+  resources:
+  - syndesises
+  - syndesises/finalizers
+  verbs: [ get, list, create, update, delete, deletecollection, watch ]
+- apiGroups:
+  - route.openshift.io
+  resources:
+  - routes/custom-host
+  verbs: [ get, list, create, update, delete, deletecollection, watch ]
+---
+
+EOT
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Can not install role 'syndesis-extra-permissions'. Are you running as cluster-admin ?"
+            exit 1
+        fi
+    fi
+
+    oc policy add-role-to-user --role-namespace="$(oc project -q)" syndesis-extra-permissions $user
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Can not add role 'syndesis-extra-permssionns' to user $user. Does the user exist ?"
+        exit 1
+    fi
+    set -e
+}
 
 recreate_project() {
     local project=$1
@@ -76,110 +226,218 @@ recreate_project() {
     oc project "${project}"
 }
 
-create_oauthclient() {
-    local tag=${1:-master}
-    create_openshift_resource \
-        "install/support/serviceaccount-as-oauthclient-restricted.yml" \
-        "$tag"
+check_oc_version()
+{
+    local minimum=${OC_MIN_VERSION}
+    local test=$(oc version | grep oc | tr -d oc\ v | cut -f1 -d "+")
+
+    echo $(compare_oc_version $test $minimum)
 }
 
-create_and_apply_template() {
-    local route=$1
-    local console=${2:-}
-    local template=${3:-syndesis}
-    local tag=${4:-}
+setup_oc() {
 
-    if [ -z "$route" ]; then
-        echo "No route given"
-        exit 1
+    # Check path first if it already exists
+    set +e
+    which oc &>/dev/null
+    if [ $? -eq 0 ]; then
+      set -e
+      err=$(check_oc_version)
+      check_error $err
+      return
     fi
 
-    create_openshift_resource \
-        "install/${template}.yml" \
-        "$tag"
+    # Check for minishift
+    which minishift &>/dev/null
+    if [ $? -eq 0 ]; then
+      set -e
+      eval $(minishift oc-env)
+      err=$(check_oc_version)
+      check_error $err
+      return
+    fi
 
-    oc new-app --template "$(get_template_name $template $tag)"\
-      -p ROUTE_HOSTNAME="${route}" \
-      -p OPENSHIFT_CONSOLE_URL="$console" \
-      -p OPENSHIFT_MASTER="$(oc whoami --show-server)" \
-      -p OPENSHIFT_PROJECT="$(oc project -q)" \
-      -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client)
+    set -e
+
+    # Error, no oc found
+    echo "ERROR: No 'oc' binary found in path. Please install the client tools from https://github.com/openshift/origin/releases/tag/v3.9.0 (or newer)"
+    exit 1
 }
 
-# Try first a template with the tag as combination
-get_template_name() {
-    local template=$1
-    local tag=${2:-}
-    if [ -n "$tag" ]; then
-        local candidate="$template-$tag"
-        $(oc get template $candidate >/dev/null 2>&1)
-        if [ $? -eq 0 ]; then
-          echo $candidate
-          return
+compare_version_part() {
+    local test=$1
+    local min=$2
+
+    test=`expr $test`
+    min=`expr $min`
+
+    if [ $test -eq $min ]; then
+        echo 0;
+    elif [ $test -gt $min ]; then
+        echo 1;
+    else
+        # $test -lt $min
+        echo -1
+    fi
+}
+
+compare_oc_version() {
+    local test=$1
+    local min=$2
+
+    echo -n "Testing oc version '$test' against required minimum '$min' ... "
+
+    testparts=( ${test//./ } )
+    minparts=( ${min//./ } )
+
+    local i=0
+    while [ $i -lt ${#minparts[@]} ]
+    do
+        local testpart=${testparts[$i]}
+        local minpart=${minparts[$i]}
+
+        if [ -z "$testpart" ]; then
+            # test version does not extend as far as minimum
+            # in parts so append a 0
+            testpart=0
+        fi
+
+        ret=$(compare_version_part $testpart $minpart)
+        if [ $ret == -1 ]; then
+            #
+            # version part is less than minimum while all preceding
+            # parts were equal so version does not meet minimum
+            #
+            echo "ERROR: oc version ($test) should be at least $min"
+            return
+        elif [ $ret == 1 ]; then
+            #
+            # version part is greater than minimum so no need to test
+            # any further parts as version is greater than minimum
+            #
+            echo "OK"
+            return
+        fi
+
+        #
+        # Only if the version part is equal will the loop continue
+        # with further parts.
+        #
+        i=`expr $i + 1`
+    done
+
+    echo "OK"
+}
+
+# Deploy operator
+deploy_syndesis_operator() {
+    local operator_installed=$(oc get dc -o name | grep syndesis-operator)
+    if [ -n "$operator_installed" ]; then
+        local result=$(delete_openshift_resource "install/operator/deploy/syndesis-operator.yml")
+        check_error $result
+        wait_for_deployments 0 syndesis-operator >/dev/null 2>&1
+    fi
+
+    local result=$(create_openshift_resource "install/operator/deploy/syndesis-operator.yml")
+    check_error $result
+}
+
+create_openshift_resource() {
+    create_or_delete_openshift_resource "create" "${1:-}"
+}
+
+delete_openshift_resource() {
+    create_or_delete_openshift_resource "delete --ignore-not-found" "${1:-}"
+}
+
+create_or_delete_openshift_resource() {
+    local what=${1}
+    local resource=${2:-}
+    local tag="$(readopt --tag)"
+    local result
+
+    set +e
+    local url="https://raw.githubusercontent.com/syndesisio/syndesis/${tag:-master}/${resource}"
+    result=$(oc $what -f $url >$ERROR_FILE 2>&1)
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Cannot create remote resource $url"
+    fi
+    set -e
+}
+
+# Create syndesis resource
+create_syndesis() {
+    local route="${1:-}"
+    local console="${2:-}"
+
+    local syndesis_installed=$(oc get syndesis -o name | wc -l)
+    local force=$(hasflag --force)
+    if [ $syndesis_installed -gt 0 ]; then
+        if [ -n "${force}" ]; then
+            oc delete $(oc get syndesis -o name)
         fi
     fi
 
+    local syndesis=$(cat <<EOT
+apiVersion: "syndesis.io/v1alpha1"
+kind: "Syndesis"
+metadata:
+  name: "app"
+spec:
+EOT
+)
+    local extra=""
+    if [ -n "$console" ]; then
+        extra=$(cat <<EOT
 
-    echo $template
+  openShiftConsoleUrl: $console
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+    if [ -n "$route" ]; then
+        extra=$(cat <<EOT
+
+  routeHostname: $route
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+
+    echo "$syndesis" | cat | oc create -f -
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Error while creating resource"
+        echo "$syndesis"
+        return
+    fi
 }
 
-guess_route() {
-    local project=${1:-}
-    if [ -z "${project}" ]; then
-        project=$(oc project -q)
-    fi
-    local log=$(oc create service clusterip smokeservice --tcp=4343 2>&1 && \
-                oc create route edge --service=smokeservice 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot create pivot route\n$log"
-        exit 1
-    fi
-    local domain=$(oc get route smokeservice -o template  --template='{{.spec.host}}' 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot extract route: $domain"
-        exit 1
-    fi
-    log=$(oc delete service smokeservice 2>&1 && \
-          oc delete route smokeservice 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot delete pivot route\n$log"
-        exit 1
-    fi
-    echo "${project}.${domain#*.}"
+wait_for_deployments() {
+  local replicas_desired=$1
+  shift
+  local dcs="$@"
+
+  oc get pods -w &
+  watch_pid=$!
+  for dc in $dcs; do
+      echo "Waiting for $dc to be scaled to ${replicas_desired}"
+      local replicas=$(get_replicas $dc)
+      while [ -z "$replicas" ] || [ "$replicas" -ne $replicas_desired ]; do
+          echo "Sleeping 10s ..."
+          sleep 10
+          replicas=$(get_replicas $dc)
+      done
+  done
+  kill $watch_pid
 }
 
-
-create_openshift_resource() {
-    local resource=${1}
-    local tag=${2:-}
-
-    oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/${tag:-master}/${resource}
-}
-
-wait_for_syndesis_to_be_ready() {
-    # Wait a bit to start image fetching
-    oc get pods -w &
-    watch_pid=$!
-    for dc in "syndesis-server" "syndesis-ui" "syndesis-meta"; do
-        echo "Waiting for $dc to be started"
-        local replicas="$(oc get dc $dc -o jsonpath='{.status.availableReplicas}')"
-        while [ "$replicas" -lt 1 ]; do
-            echo "Sleeping 10s ..."
-            sleep 10
-            replicas=$(oc get dc $dc -o jsonpath="{.status.availableReplicas}")
-        done
-    done
-    kill $watch_pid
-}
-
-probe_commands() {
-    for cmd in $@; do
-      local ret=$(which $cmd 2>/dev/null)
-      if [ $? -eq 0 ]; then
-          echo $ret
-          return
-      fi
-    done
+get_replicas() {
+  local dc=${1}
+  local hasDc=$(oc get dc -o name | grep $dc)
+  if [ -z "$hasDc" ]; then
+      echo "0"
+      return
+  fi
+  oc get dc $dc -o jsonpath="{.status.availableReplicas}"
 }
 
 open_url() {
@@ -193,66 +451,52 @@ open_url() {
     exec $cmd $url
 }
 
-# Checks if a flag is present in the arguments.
-hasflag() {
-    filters="$@"
-    for var in $ARGS; do
-        for filter in $filters; do
-          if [ "$var" = "$filter" ]; then
-              echo 'true'
-              return
-          fi
-        done
+probe_commands() {
+    for cmd in $@; do
+      local ret=$(which $cmd 2>/dev/null)
+      if [ $? -eq 0 ]; then
+          echo $ret
+          return
+      fi
     done
-}
-
-# Read the value of an option.
-readopt() {
-    filters="$@"
-    next=false
-    for var in $ARGS; do
-        if $next; then
-            echo $var
-            break;
-        fi
-        for filter in $filters; do
-            if [[ "$var" = ${filter}* ]]; then
-                local value="${var//${filter}=/}"
-                if [ "$value" != "$var" ]; then
-                    echo $value
-                    return
-                fi
-                next=true
-            fi
-        done
-    done
-}
-
-check_error() {
-    local msg="$*"
-    if [ "${msg//ERROR/}" != "${msg}" ]; then
-        echo $msg
-        exit 1
-    fi
 }
 
 # ==============================================================
 
+if [ $(hasflag --help -h) ]; then
+    display_usage
+    exit 0
+fi
+
+ERROR_FILE="$(mktemp /tmp/syndesis-output-XXXXX)"
+trap "print_error $ERROR_FILE" EXIT
+
 if [ $(hasflag --verbose -v) ]; then
-    export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+    export PS4='+($(basename ${BASH_SOURCE[0]}):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
     set -x
 fi
 
-tag=$(readopt --tag -t)
-route=$(readopt --route -r)
-console=$(readopt --console)
-
-# Get route
-route=$(readopt --route)
-if [ -z "${route}" ]; then
-    route="$(guess_route "$project")"
-    check_error $route
+prep_only="false"
+if [ $(hasflag -s --setup-as-admin) ]; then
+    echo "Installing Syndesis CRD"
+    result=$(install_syndesis_crd)
+    check_error "$result"
+    prep_only="true"
 fi
+
+user_to_prepare="$(readopt -u --prepare-for-user)"
+if [ -n  "$user_to_prepare" ]; then
+    echo "Grant permission to create Syndesis to user $user_to_prepare"
+    result=$(add_user_permissions_for_operator "$user_to_prepare")
+    check_error "$result"
+    prep_only="true"
+fi
+
+if $prep_only; then
+    exit 0
+fi
+
+# ==================================================================
 
 # If a project is given, create it new or recreate it
 project=$(readopt --project -p)
@@ -260,21 +504,37 @@ if [ -n "${project}" ]; then
     recreate_project $project
 fi
 
-if [ -z "${route}" ]; then
-    route="$(guess_route "${project}")"
-    check_error "$route"
+# Check for OC
+setup_oc
+
+# Check for the proper setup
+set +e
+oc get syndesis >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+    check_error "ERROR: No CRD Syndesis installed or not enough rights. Please run --setup-as-admin and/or --prepare-for-user as cluster-admin. See 'syndesis install --help' for more information."
 fi
+set -e
 
-# Required OAuthclient
-create_oauthclient "$tag"
+# Deploy operator and wait until its up
+echo "Deploying Syndesis operator"
+result=$(deploy_syndesis_operator)
+check_error "$result"
+wait_for_deployments 1 syndesis-operator
 
-# Apply a template, based on the given arguments
-create_and_apply_template "$route" "$console" "" "$tag"
+# Create syndesis resource
+echo "Creating Syndesis resource"
+route=$(readopt --route)
+console=$(readopt --console)
+result=$(create_syndesis "$route" "$console")
+check_error "$result"
 
 if [ $(hasflag --watch -w) ] || [ $(hasflag --open -o) ]; then
-    wait_for_syndesis_to_be_ready
+    wait_for_deployments 1 syndesis-server syndesis-ui syndesis-meta
 fi
 
+# ==========================================================
+
+tag=$(readopt --tag -t)
 if [ -n "$tag" ]; then
     label="Syndesis $tag"
 else
