WIP

diff --git a/tools/bin/commands/install b/tools/bin/commands/install
--- a/tools/bin/commands/install
+++ b/tools/bin/commands/install
@@ -20,8 +20,6 @@ install::usage() {
                               version from master is installed
     --force                   Override an existing "Syndesis" if present
 -w  --watch                   Wait until cluster is up
-    --local                   install from local Git repo when using. By default the resource descriptor is
-                              downloaded from GitHub remotely.
 -f  --force-binary-download   By default if the binary cli is present in the expected path, it will
                               be used. With this option enabled, the binary will be removed and downloaded,
                               ensuring it is the latest version
@@ -39,9 +37,54 @@ install::usage() {
 EOT
 }
 
+#
+# Checks where the syndesis-installer role has been grant to the project
+#
+is_role_granted() {
+    local user=$(get_current_user)
+
+    ${KUBE} get rolebinding syndesis-installer-${user} > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # Have a role binding for this user so return
+        echo "OK"
+        return
+    fi
+
+    ${KUBE} get clusterrolebinding syndesis-installer-${user} > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # Have a cluster role binding for this user so return
+        echo "OK"
+        return
+    fi
+
+    echo "ERROR: The user '${user}' does not have the 'syndesis-installer' role. Please execute '... --grant' as a cluster-admin first."
+}
+
+grant_role() {
+  local user_to_prepare="$1"
+  if [ -z "$user_to_prepare" ]; then
+    check_error "ERROR: Cannot perform grant as no user specified"
+  fi
+
+  echo "Grant syndesis-installer role to user $user_to_prepare"
+
+  #
+  # Check that the user calling --grant is a cluster-admin
+  #
+  if [ $(is_cluster_admin) != "OK" ]; then
+    check_error "ERROR: Can only execute --grant as cluster-admin."
+  fi
+
+  if [ $(hasflag --cluster) ]; then
+      result=$($OPERATOR_BINARY grant --user $user_to_prepare --cluster)
+  else
+      result=$($OPERATOR_BINARY grant --user $user_to_prepare)
+  fi
+  check_error "$result"
+}
 
 install::run() {
-    source "$(basedir)/commands/util/openshift_funcs"
+    source "$(basedir)/commands/util/client_funcs"
     source "$(basedir)/commands/util/camel_k_funcs"
     source "$(basedir)/commands/util/operator_funcs"
 
@@ -53,15 +96,35 @@ install::run() {
     fi
     download_operator_binary || print_error_and_exit "unable to download the operator binary, exit"
 
+    #
+    # If a project is given, only a cluster-admin
+    # can create it new or recreate it
+    #
+    project=$(readopt --project -p)
+    if [ -n "${project}" ]; then
+        if [ "$(is_cluster_admin)" == "OK" ]; then
+            recreate_namespace $project
+        else
+            check_error "ERROR: It is not possible to install into a new (or recreated) project without being a cluster-admin since artifacts required by the install cannot be (re)created."
+        fi
+    fi
+
     local prep_only="false"
     if [[ $(hasflag -s --setup) ]]; then
         echo "Installing Syndesis CRD"
+
+        #
+        # Need to be a cluster admin for this to happen
+        #
+        result=$(is_cluster_admin)
+        check_error "${result}"
+
         result=$($OPERATOR_BINARY install cluster)
         check_error "$result"
         if [ $(hasflag --camel-k) ]; then
-          echo "Installing Camel-K CRDs"
-          result=$(install_camel_k_crds "$(readopt --camel-k)")
-          check_error "$result"
+            echo "Installing Camel-K CRDs"
+            result=$(install_camel_k_crds "$(readopt --camel-k)")
+            check_error "$result"
         fi
         prep_only="true"
     fi
@@ -69,13 +132,14 @@ install::run() {
     local user_to_prepare="$(readopt -u --grant)"
     if [ -n  "$user_to_prepare" ]; then
         echo "Grant permission to create Syndesis to user $user_to_prepare"
-        if [ $(hasflag --cluster) ]; then
-            result=$($OPERATOR_BINARY grant --user $user_to_prepare --cluster)
-        else
-            result=$($OPERATOR_BINARY grant --user $user_to_prepare)
 
-        fi
-        check_error "$result"
+        #
+        # Need to be a cluster admin for this to happen
+        #
+        result=$(is_cluster_admin)
+        check_error "${result}"
+
+        grant_role "${user_to_prepare}"
         prep_only="true"
     fi
 
@@ -91,24 +155,36 @@ install::run() {
         fi
     fi
 
-    # If a project is given, create it new or recreate it
-    local project=$(readopt --project -p)
-    if [ -n "${project}" ]; then
-        recreate_project $project "$(hasflag --yes -y)"
+    #
+    # If a cluster-admin and the role has not yet been granted
+    # then ensure it is by granting it to the current user
+    #
+    if [ "$(is_cluster_admin)" == "OK" ]; then
+      if [ "$(is_role_granted)" != "OK" ]; then
+        echo "No syndesis-installer role has been granted so installing now"
+        grant_role "$(get_current_user)"
+      fi
     fi
 
-    # Setup oc
-    setup_oc
+    #
+    # Check that user has syndesis-installer role available
+    #
+    result=$(is_role_granted)
+    check_error "$result"
 
-    # Check for the proper setup
-    set +e
-    oc get syndesis >/dev/null 2>&1
+    #
+    # Check Syndesis CRD installed
+    #
+    ${KUBE} get syndesis >/dev/null 2>&1
     if [ $? -ne 0 ]; then
         check_error "ERROR: No CRD Syndesis installed or not enough permissions to read them. Please run --setup and/or --grant as cluster-admin. See 'syndesis install --help' for more information."
     fi
 
+    #
+    # If using camel-k, check CRD installed
+    #
     if [ $(hasflag --camel-k) ]; then
-        oc get integration >/dev/null 2>&1
+        ${KUBE} get integration >/dev/null 2>&1
         if [ $? -ne 0 ]; then
             check_error "ERROR: Camel-K installation requested but no Camel-K CRDs accessible. Please run --setup --camel-k to register the proper CRDs."
         fi
@@ -116,8 +192,14 @@ install::run() {
     set -e
 
     if [ $(hasflag --maven-mirror) ]; then
-        install_maven_mirror
+        create_maven_mirror
     fi
+
+    #
+    # Execute any preparatory tasks before installing the operator
+    #
+    execute_pre_tasks
+
 
     # Deploy operator and wait until its up
     echo "Deploying Syndesis operator"
@@ -126,7 +208,7 @@ install::run() {
 
     if [ $(hasflag --camel-k) ]; then
         echo "Deploying Camel-K operator"
-        result=$(deploy_camel_k_operator "$(readopt --camel-k)" "$(oc project -q)" "$(readopt --camel-k-options)")
+        result=$(deploy_camel_k_operator "$(readopt --camel-k)" "$(${KUBE} project -q)" "$(readopt --camel-k-options)")
         check_error "$result"
     fi
 
@@ -138,8 +220,7 @@ install::run() {
         exit 0
     else
         # Deploying syndesis app
-        local customcr=$(readopt --custom-resource)
-
+        local customcr=$(get_custom_resource $(readopt --custom-resource))
         if [ -n "${customcr}" ]; then
             echo "Deploying syndesis app with custom resource ${customcr}"
             app_options=$app_options" --custom-resource ${customcr}"
@@ -157,10 +238,10 @@ install::run() {
     fi
 
     if [ $(hasflag --open -o) ]; then
-        while ! (oc get routes | grep syndesis >/dev/null 2>&1); do
+        while ! (${KUBE} get routes | ${GREP} syndesis >/dev/null 2>&1); do
             echo "Sleeping 5s ..."
             sleep 5
         done
-        open_url "https://$(oc get routes syndesis --template "{{.spec.host}}")"
+        open_url "https://$(${KUBE} get routes syndesis --template "{{.spec.host}}")"
     fi
 }
diff --git a/tools/bin/commands/util/common_funcs b/tools/bin/commands/util/common_funcs
--- a/tools/bin/commands/util/common_funcs
+++ b/tools/bin/commands/util/common_funcs
@@ -3,15 +3,24 @@
 # Minimal version for GO
 GO_MIN_VERSION=1.12
 
+# Version of the platform detect binary
+PLATFORM_DETECT_VERSION="0.1.0"
+
+# Var to hold result of detecting platform is openshift
+IS_OPENSHIFT=""
+
+# Commands that may have alternatives
+GREP="grep"
+
 # Checks if a flag is present in the arguments.
 hasflag() {
     filters="$@"
     for var in "${ARGS[@]}"; do
         for filter in $filters; do
-          if [ "$var" = "$filter" ]; then
-              echo 'true'
-              return
-          fi
+            if [ "$var" = "$filter" ]; then
+                echo 'true'
+                return
+            fi
         done
     done
 }
@@ -48,12 +57,12 @@ readopt() {
         if $next; then
             local value="${var##-}"
             if [ "$value" != "$var" ]; then
-               # Next is already also option, so we haven't
-               # specified a value.
-               return
+                # Next is already also option, so we haven't
+                # specified a value.
+                return
             fi
             echo $var
-            break;
+            break
         fi
         for filter in $filters; do
             if [[ "$var" = ${filter}* ]]; then
@@ -68,18 +77,17 @@ readopt() {
     done
 }
 
-
 check_error() {
     local msg="$*"
-    if [ "${msg//ERROR/}" != "${msg}" ]; then
-        if [ -n "${ERROR_FILE:-}" ] && [ -f "$ERROR_FILE" ] && ! grep "$msg" $ERROR_FILE ; then
+    if awk 'BEGIN {exit !index(toupper(ARGV[2]), toupper(ARGV[1]))}' "ERROR" "$msg"; then
+        if [ -n "${ERROR_FILE:-}" ] && [ -f "$ERROR_FILE" ] && ! ${GREP} "$msg" $ERROR_FILE; then
             local tmp=$(mktemp /tmp/error-XXXX)
-            echo ${msg} >> $tmp
+            echo ${msg} >>$tmp
             if [ $(wc -c <$ERROR_FILE) -ne 0 ]; then
-              echo >> $tmp
-              echo "===============================================================" >> $tmp
-              echo >> $tmp
-              cat $ERROR_FILE >> $tmp
+                echo >>$tmp
+                echo "===============================================================" >>$tmp
+                echo >>$tmp
+                cat $ERROR_FILE >>$tmp
             fi
             mv $tmp $ERROR_FILE
         fi
@@ -87,10 +95,20 @@ check_error() {
     fi
 }
 
+has_error() {
+  local msg="$*"
+  if awk 'BEGIN {exit !index(toupper(ARGV[2]), toupper(ARGV[1]))}' "ERROR" "$msg"; then
+      return 0
+  else
+      return 1
+  fi
+}
+
 print_error() {
     local exit_code=$?
     local error_file="${1:-}"
-    if [ -f $error_file ] && grep -q "ERROR" $error_file; then
+
+    if [ -f $error_file ] && ${GREP} -qi "ERROR" $error_file; then
         cat $error_file
     elif [ $exit_code -ne 0 ]; then
         echo "ERROR: Last command exited with $exit_code"
@@ -112,69 +130,176 @@ open_url() {
     exec $cmd $url
 }
 
+# check that a given binary is in $PATH
+check_for_command() {
+    local cmd=$1
+    if [ -z "$cmd" ]; then
+        echo "ERROR: command not specified to check_for_command"
+        return
+    fi
+
+    if $(command -v $cmd >/dev/null 2>&1); then
+        echo "OK"
+        return
+    fi
+
+    echo "ERROR: command '$cmd' is required but not available on PATH"
+}
+
 probe_commands() {
     for cmd in $@; do
-      local ret=$(which $cmd 2>/dev/null)
-      if [ $? -eq 0 ]; then
-          echo $ret
-          return
-      fi
+        local ret=$(which $cmd 2>/dev/null)
+        if [ $? -eq 0 ]; then
+            echo $ret
+            return
+        fi
     done
 }
 
 # Syndesis config dir holding state across builds
 syndesis_config_dir() {
-  local dir="$HOME/.syndesis";
-  [ -d $dir ] || mkdir $dir;
-  echo $dir
+    local dir="$HOME/.syndesis"
+    [ -d $dir ] || mkdir $dir
+    echo $dir
 }
 
 # ======================================================
 # Git update functions
 git_rebase_upstream() {
-  echo "git fetch upstream master"
-  git fetch upstream master
-  echo -n "git rebase upstream/master"
-  if ! git rebase upstream/master; then
-    echo " (failed)"
-    echo "git stash"
-    git stash
-    echo "git rebase upstream/master"
-    git rebase upstream/master
-    echo "git stash pop"
-    git stash pop
-  else
-    echo
-  fi
+    echo "git fetch upstream master"
+    git fetch upstream master
+    echo -n "git rebase upstream/master"
+    if ! git rebase upstream/master; then
+        echo " (failed)"
+        echo "git stash"
+        git stash
+        echo "git rebase upstream/master"
+        git rebase upstream/master
+        echo "git stash pop"
+        git stash pop
+    else
+        echo
+    fi
 }
 
 # returns `"true"` if subtree path has changes
 has_changes() {
-  local subtree_path="${1:-}"
-  local ref="${2:-master}"
-  local hash="${CIRCLE_SHA1:-$(git rev-parse HEAD)}"
+    local subtree_path="${1:-}"
+    local ref="${2:-master}"
+    local hash="${CIRCLE_SHA1:-$(git rev-parse HEAD)}"
 
-  local changed_paths="$(git diff ..${ref} --name-only | tr '\n' ' ') $(git status --porcelain=v1 | cut -c 4- | tr '\n' ' ')"
+    local changed_paths="$(git diff ..${ref} --name-only | tr '\n' ' ') $(git status --porcelain=v1 | cut -c 4- | tr '\n' ' ')"
 
-  # when on `master` on CircleCI, compute changed paths for the commit being built
-  if [ "master" == "${CIRCLE_BRANCH:-}" ]; then
-    changed_paths="$changed_paths $(git log $hash^..$hash --name-only --pretty='format:' | tr '\n' ' ')"
-  fi
-  if [[ " $changed_paths" == *" ${subtree_path}"* ]]; then
-    echo "true"
-  fi
+    # when on `master` on CircleCI, compute changed paths for the commit being built
+    if [ "master" == "${CIRCLE_BRANCH:-}" ]; then
+        changed_paths="$changed_paths $(git log $hash^..$hash --name-only --pretty='format:' | tr '\n' ' ')"
+    fi
+    if [[ " $changed_paths" == *" ${subtree_path}"* ]]; then
+        echo "true"
+    fi
+}
+
+#
+# Download `platform-detect` binary
+#
+get_platform_detect_bin() {
+    local version=${1:-$PLATFORM_DETECT_VERSION}
+    local bin_name="platform-detect"
+    local binary="${bin_name}-${version}"
+
+    check_error $(check_for_command "mktemp")
+    check_error $(check_for_command "mkdir")
+    check_error $(check_for_command "curl")
+    check_error $(check_for_command "tar")
+    check_error $(check_for_command "rm")
+    check_error $(check_for_command "mv")
+
+    #
+    # If its already downloaded, skip download
+    #
+    local config_dir=$(syndesis_config_dir)
+    [ -d ${config_dir}/bin ] || mkdir -p ${config_dir}/bin
+
+    local detect_command="${config_dir}/bin/${binary}"
+    if [ -e ${detect_command} ]; then
+        echo ${detect_command}
+        return
+    fi
+
+    #
+    # Check for proper operating system
+    #
+    local os="linux"
+    if $(isMacOs); then
+        os="mac"
+    elif $(isWindows); then
+        os="windows"
+    fi
+
+    #
+    # Download from site
+    #
+    local base_url="https://github.com/syndesisio/syndesis/releases/download/$version"
+    local download_url="${base_url}/platform-detect-$version-$os-amd64.tar.gz"
+    local archive=$(mktemp ${config_dir}/platform-detect-${version}.tar-XXXX)
+    curl -sL --fail -o ${archive} ${download_url} 2>/dev/null || { check_error "ERROR: Could not download ${binary} from ${download_url}"; }
+
+    #
+    # Extract binary and move to correct name
+    #
+    local tmp_dir=$(mktemp -d ${config_dir}/platform-detect-${version}-XXXX)
+    pushd ${tmp_dir} >/dev/null
+
+    tar xf ${archive} >/dev/null
+    rm ${archive}
+
+    if [ ! -f ./${bin_name} ]; then
+        check_error "ERROR: Failed to extract ${bin_name} to ${tmp_dir}/"
+    fi
+
+    mv ./${bin_name} ${detect_command}
+
+    popd >/dev/null
+
+    #
+    # Clean up temporary directories
+    #
+    [ -n "$tmp_dir" ] && [ -d "$tmp_dir" ] && rm -rf $tmp_dir
+    echo $detect_command
+}
+
+determine_platform() {
+    if [ ! -z $IS_OPENSHIFT ]; then
+      return
+    fi
+
+    check_error $(check_for_command "echo")
+    check_error $(check_for_command "awk")
+
+    local detect=$(get_platform_detect_bin)
+    check_error "${detect}"
+
+    local result=$($detect)
+    check_error "$result"
+
+    local os=$(echo "$result" | ${GREP} Openshift | awk '{print $2}')
+    if [ "$os" == "true" ]; then
+        IS_OPENSHIFT=true
+    else
+        IS_OPENSHIFT=false
+    fi
 }
 
 docker_is_available() {
     set +e
-    which docker &>/dev/null
-    if [ $? -ne 0 ]; then
+
+    if [ $(check_for_command "docker") != "OK" ]; then
         set -e
         echo "ERROR: 'docker' command not installed"
         return
     fi
 
-    if docker info > /dev/null 2> /dev/null ; then
+    if docker info >/dev/null 2>&1; then
         echo "OK"
     else
         echo "ERROR: the 'docker' command is not connected to a server"
@@ -185,8 +310,8 @@ docker_is_available() {
 
 go_is_available() {
     set +e
-    which go &>/dev/null
-    if [ $? -ne 0 ]; then
+
+    if [ $(check_for_command "go") != "OK" ]; then
         set -e
         echo "ERROR: 'go' command not installed"
         return
@@ -199,7 +324,7 @@ go_is_available() {
     fi
 
     gocompare=$(compare_version $test $GO_MIN_VERSION \"go\")
-    if [[ "$gocompare" != "OK" ]] ; then
+    if [[ "$gocompare" != "OK" ]]; then
         set -e
         echo "ERROR: 'go' command ($test) does not meet the minimum version of $GO_MIN_VERSION"
         return
@@ -210,43 +335,33 @@ go_is_available() {
     echo "OK"
 }
 
-set_gnugrep() {
-    if $(isMacOs); then
-        if [ $(ggrep_is_available_on_osx) == "OK" ]; then
-            gnugrep=`which ggrep`
-        else
-            echo "ERROR: 'Please install ggrep on OSX'"
-            return
-        fi
-    else
-      gnugrep=`which grep`
-    fi
-}
+gnugrep() {
+    check_error $(check_for_command "which")
 
-ggrep_is_available_on_osx() {
-    set +e
-    which ggrep &>/dev/null
-    if [ $? -ne 0 ]; then
-        set -e
-        echo "Please install GNU grep using: brew install grep"
-        return
+    if $(isMacOs); then
+
+      if $(check_for_command "ggrep") -ne "OK" ]; then
+        check_error "ERROR: Please install ggrep on OSX usimg 'brew install grep'"
+      else
+        GREP=$(which ggrep)
+      fi
+
+    else
+        GREP=$(which grep)
     fi
-    set -e
-    
-    echo "OK"
 }
 
 compare_version_part() {
     local test=$1
     local min=$2
 
-    test=`expr $test`
-    min=`expr $min`
+    test=$(expr $test)
+    min=$(expr $min)
 
     if [ $test -eq $min ]; then
-        echo 0;
+        echo 0
     elif [ $test -gt $min ]; then
-        echo 1;
+        echo 1
     else
         # $test -lt $min
         echo -1
@@ -257,12 +372,11 @@ compare_version() {
     local test=$1
     local min=$2
 
-    testparts=( ${test//./ } )
-    minparts=( ${min//./ } )
+    testparts=(${test//./ })
+    minparts=(${min//./ })
 
     local i=0
-    while [ $i -lt ${#minparts[@]} ]
-    do
+    while [ $i -lt ${#minparts[@]} ]; do
         local testpart=${testparts[$i]}
         local minpart=${minparts[$i]}
 
@@ -293,7 +407,7 @@ compare_version() {
         # Only if the version part is equal will the loop continue
         # with further parts.
         #
-        i=`expr $i + 1`
+        i=$(expr $i + 1)
     done
 
     echo "OK"
