feature(syndesis minishift): Pick up oc from minishift
if oc is not found in the path, but minishift. Also updated README
to refer to the doc.syndsis.io + a super short quickstart.

diff --git a/tools/bin/commands/minishift b/tools/bin/commands/minishift
--- a/tools/bin/commands/minishift
+++ b/tools/bin/commands/minishift
@@ -9,9 +9,9 @@ minishift::usage() {
     --install                 Install templates to a running Minishift.
 -p  --project                 Install into this project. Delete this project if it already exists
 -c  --context                 Install into this context. Default is 'minishift'
-    --reset                   Reset the minishift installation by
+    --reset                   Reset and initialize the minishift installation by
                               'minishift delete && minishift start'.
-    --full-reset              Full reset by
+    --full-reset              Full reset and initialie by
                               'minishift stop && rm -rf ~/.minishift && minishift start'
     --memory <mem>            How much memory to use when doing a reset. Default: 4GB
     --cpus <nr cpus>          How many CPUs to use when doing a reset. Default: 2
@@ -34,25 +34,26 @@ EOT
 minishift::run() {
     source "$(basedir)/commands/util/openshift_funcs"
 
-    if [ $(hasflag --open -o) ]; then
-        open_url "$(minishift openshift service syndesis-oauthproxy --url)"
+    # Check that mininishift is installed
+    which minishift &>/dev/null
+    if [ $? -ne 0 ]; then
+        echo "ERROR: No 'minishift' found in path."
+        echo "Please insall Minishift from https://github.com/MiniShift/minishift"
+        exit 1
     fi
+
     if [ $(hasflag --full-reset) ] || [ $(hasflag --reset) ]; then
-        # Only warning if minishift is not installed
-        minishift delete --clear-cache --force
-        if [ $(hasflag --full-reset) ] && [ -d ~/.minishift ]; then
-            rm -rf ~/.minishift
-        fi
-        local memory=$(readopt --memory)
-        local cpus=$(readopt --cpus)
-        local disksize=$(readopt --disk-size)
-        local show_logs_arg=""
-        local openshift_version=$(readopt --openshift-version)
-        if [ $(hasflag --show-logs --show-log) ]; then
-            show_logs_args="--show-libmachine-logs=true "
-        fi
-        minishift start ${show_logs_arg:- }--memory ${memory:-4912} --cpus ${cpus:-2} --disk-size ${disksize:-20GB} --openshift-version ${openshift_version:-v3.6.0}
+        delete_minishift $(hasflag --full-reset)
+        start_minishift
     fi
+
+    # Start minishift if necessary
+    if [ -n "$(is_minishift_running)" ]; then
+      start_minishift
+    fi
+
+    # Ensure OC is in the bath
+    setup_oc
 
     if [ $(hasflag --install) ]; then
 
@@ -83,4 +84,44 @@ minishift::run() {
           patch_imagestreams_for_initial_image
         fi
     fi
+
+    if [ $(hasflag --open -o) ]; then
+        open_url "$(minishift openshift service syndesis-oauthproxy --url)"
+    fi
+}
+
+is_minishift_running() {
+    set +e
+    minishift status 2>&1 | grep -q "Running"
+    local stat=$?
+    set -e
+    if [ $? -eq 0 ]; then
+      echo "true"
+    fi
+}
+
+delete_minishift() {
+    local remove_all=${1:-}
+
+    if [ $(is_minishift_running) ]; then
+      minishift stop
+    fi
+
+    minishift delete --clear-cache --force
+    if [ $remove_all ] && [ -d ~/.minishift ]; then
+        rm -rf ~/.minishift
+    fi
+}
+
+start_minishift() {
+    local memory=$(readopt --memory)
+    local cpus=$(readopt --cpus)
+    local disksize=$(readopt --disk-size)
+    local openshift_version=$(readopt --openshift-version)
+    local show_logs_arg=""
+    if [ $(hasflag --show-logs --show-log) ]; then
+        show_logs_args="--show-libmachine-logs=true "
+    fi
+    echo "Starting minishift ...."
+    minishift start ${show_logs_arg:-}--memory ${memory:-4912} --cpus ${cpus:-2} --disk-size ${disksize:-20GB} --openshift-version ${openshift_version:-v3.6.0}
 }
