fix(release): tagging moving version of operato...
...r image

(cherry picked from commit f8c44c97ee8052b966baee6db2303832cd7426b6)

diff --git a/tools/bin/commands/release b/tools/bin/commands/release
--- a/tools/bin/commands/release
+++ b/tools/bin/commands/release
@@ -95,6 +95,9 @@ release::run() {
     # Set pom.xml version to the given release_version
     update_pom_versions "$topdir" "$release_version" "$maven_opts"
 
+    # Updates install/operator/deploy/syndesis-operator.yml
+    generate_versioned_files "$topdir" "$release_version"
+
     # Build and stage artefacts to Sonatype
     build_and_stage_artefacts "$topdir" "$maven_opts"
 
@@ -130,7 +133,8 @@ release::run() {
     # Tag the release version
     git_tag_release "$release_version"
 
-    # Create template versions for the minor tags (without patchlevels)
+    # Create operator deploy YAMLs, image versions for the minor tags (without patchlevels)
+    # and commit to git
     create_moving_tag_release "$topdir" "$release_version" "$moving_tag"
 
     # Pushing to Docker Hub
@@ -149,7 +153,14 @@ create_moving_tag_release() {
     local moving_tag=$3
 
     if [ ! $(hasflag --snapshot-release) ]; then
+        generate_versioned_files "$topdir" "$moving_tag" "$release_version"
+
+        docker image tag "syndesis/syndesis-operator:$release_version" "syndesis/syndesis-operator:$moving_tag"
         docker push "syndesis/syndesis-operator:$moving_tag"
+
+        echo "==== Git commit for templates and syndesis-operator.yml, $moving_tag"
+        cd $topdir
+        git_commit ^install/ "Update OpenShift templates and syndesis-operator.yml for Syndesis $moving_tag"
 
         echo "==== Git tag $moving_tag"
         git tag -f $moving_tag
@@ -231,6 +242,31 @@ get_next_version() {
     local suffix="${version##*.}"
 
     echo "$prefix"."$((suffix+1))"
+}
+
+generate_versioned_files() {
+    local dir="$1/install"
+    local tag="$2"
+    local previous_tag="${3:-latest}"
+
+    echo "==== Updating operator deployment config"
+    cd $dir/operator/deploy
+
+    sed -i.bak \
+        -e "s/syndesis-operator:${previous_tag}/syndesis-operator:$tag/" \
+        -e "s/name:[[:space:]]*'${previous_tag}'/name: '$tag'/" \
+           syndesis-operator.yml
+    rm syndesis-operator.yml.bak
+
+    # Verify that the patch worked
+    local nr_diff=$(git diff --shortstat syndesis-operator.yml | grep "3 insertions" | wc -l | xargs)
+    if [ $nr_diff -ne 1 ]; then
+        echo "Patching of syndesis-operator.yml failed"
+        cat syndesis-operator.yml
+        git diff --shortstat syndesis-operator.yml
+        git diff syndesis-operator.yml | cat -
+        exit 1
+    fi
 }
 
 build_and_stage_artefacts() {
