Update release

diff --git a/tools/bin/commands/release b/tools/bin/commands/release
--- a/tools/bin/commands/release
+++ b/tools/bin/commands/release
@@ -165,6 +165,10 @@ calc_timestamp_version() {
     local topdir=$1
     cd $topdir/app
     local pom_version=$(./mvnw -N help:evaluate -Dexpression="project.version" | grep  '^\d[^\s]*$' | sed -e 's/\([0-9]*\.[0-9]*\).*/\1/')
+    if [ -z "${pom_version}" ]; then
+        echo "ERROR: Cannot extract version from app/pom.xml"
+        exit 1
+    fi
     local patch_level=$(git tag | grep ^$pom_version | sed -e s/${pom_version}.// | sort -n -r | head -1)
     echo "${pom_version}.$((patch_level+1))-$(date '+%Y%m%d')"
 }
