fix: Release syndesis-operator.yml with the proper version

diff --git a/tools/bin/commands/release b/tools/bin/commands/release
--- a/tools/bin/commands/release
+++ b/tools/bin/commands/release
@@ -97,7 +97,7 @@ release::run() {
     mvn_clean_install "$topdir" "$maven_opts"
 
     # Create templates for the full syndesis version
-    generate_templates "$topdir" "$release_version"
+    generate_versioned_files "$topdir" "$release_version"
 
     # Build and stage artefacts to Sonatype
     build_and_stage_artefacts "$topdir" "$maven_opts"
@@ -144,22 +144,26 @@ release::run() {
     git_tag_release "$release_version"
 
     # Create template versions for the minor tags (without patchlevels)
-    create_templates_for_moving_tag "$topdir" "$moving_tag"
+    create_moving_tag_release "$topdir" "$moving_tag"
 
     # Push everything (if configured)
     git_push "$topdir" "$release_version" "$moving_tag"
 }
 
-create_templates_for_moving_tag() {
+create_moving_tag_release() {
     local topdir=$1
     local moving_tag=$2
 
     if [ ! $(hasflag --snapshot-release) ]; then
-        generate_templates $topdir $moving_tag
+        generate_versioned_files $topdir $moving_tag
 
-        echo "==== Git commit for templates $moving_tag"
+        # Recreate operator image with the versioned templates and push
+        create_operator_image "$topdir/install/operator" "true" "$moving_tag"
+        docker push "syndesis/syndesis-operator:$moving_tag"
+
+        echo "==== Git commit for templates and syndesis-operator.yml, $moving_tag"
         cd $topdir
-        git_commit ^install/ "Update OpenShift templates for Syndesis $moving_tag"
+        git_commit ^install/ "Update OpenShift templates and syndesis-operator.yml for Syndesis $moving_tag"
 
         echo "==== Git tag $moving_tag"
         git tag -f $moving_tag
@@ -219,13 +223,31 @@ mvn_clean_install() {
     ./mvnw ${maven_opts} -f "$topdir/doc/pom.xml" clean install
 }
 
-generate_templates() {
+generate_versioned_files() {
     local dir="$1/install"
-    local moving_tag="$2"
+    local tag="$2"
 
-    echo "==== Creating templates for $moving_tag"
+    echo "==== Creating templates for $tag"
     cd $dir/generator
-    sh run.sh --syndesis-tag="$moving_tag"
+    sh run.sh --syndesis-tag="$tag"
+
+    echo "==== Updating operator deployment config"
+    cd $dir/operator/deploy
+
+    sed -i.bak \
+        -e "s/syndesis-operator:latest/syndesis-operator:$tag/" \
+        -e "s/name:[[:space:]]*latest/name: $tag/" \
+           syndesis-operator.yml
+    rm syndesis-operator.yml.bak
+
+    # Verify that the patch worked
+    local nr_diff=$(git diff --shortstat syndesis-operator.yml | grep "3 insertions" | wc -l | xargs)
+    if [ $nr_diff -ne 1 ]; then
+        echo "Patching of syndesis-operator.yml failed"
+        git diff --shortstat syndesis-operator.yml
+        git diff syndesis-operator.yml | cat -
+        exit 1
+    fi
 }
 
 build_and_stage_artefacts() {
@@ -290,9 +312,14 @@ docker_push() {
     echo "==== Pushing to Docker Hub"
     for module in $ALL_IMAGE_MODULES; do
         local image="syndesis/syndesis-$module"
-        docker tag "$image:$release_version" "$image:$moving_tag"
         docker push "$image:$release_version"
-        docker push "$image:$moving_tag"
+
+        # The opertor image needs to be recreated for the moving, tag.
+        # This is done in a later step.
+        if [ $module != "operator" ]; then
+            docker tag "$image:$release_version" "$image:$moving_tag"
+            docker push "$image:$moving_tag"
+        fi
     done
 
     # Push out upgrade image
