feature(install): Changed to use new operator mechanism for "syndesis install"
and some minor, operator related fixes.

diff --git a/tools/bin/commands/util/openshift_funcs b/tools/bin/commands/util/openshift_funcs
--- a/tools/bin/commands/util/openshift_funcs
+++ b/tools/bin/commands/util/openshift_funcs
@@ -142,30 +142,20 @@ recreate_project() {
     oc project "${project}"
 }
 
-select_template() {
-    local is_dev=${1:-false}
-    if [ ${is_dev} == "true" ]; then
-        echo "syndesis-dev"
-    else
-        echo "syndesis"
-    fi
-}
-
-
 # Install the Syndesis custom resource definition
 install_syndesis_crd() {
-    set -e
+    set +e
     oc get crd >/dev/null 2>&1
     local err=$?
-    set +e
-    if [ $err != 0 ]; then
+    set -e
+    if [ $err -ne 0 ]; then
         echo "ERROR: Cannot install CRD 'Syndesis'. You have to have cluster admin permission to do this"
         return
     fi
 
     local crd_installed=$(oc get crd -o name | grep syndesises.syndesis.io)
     if [ -z "$crd_installed" ]; then
-        oc create -f $(appdir install/operator/deploy)/syndesis-crd.yml
+        create_openshift_resource "install/operator/deploy/syndesis-crd.yml"
     fi
 }
 
@@ -177,105 +167,151 @@ deploy_syndesis_operator() {
         wait_for_deployments 0 syndesis-operator
     fi
 
-    oc create -f $(appdir install/operator/deploy)/syndesis-operator.yml
+    create_openshift_resource "install/operator/deploy/syndesis-operator.yml"
 }
 
 # Create syndesis resource
 create_syndesis() {
+    local route="${1:-}"
+    local console="${2:-}"
+
     local syndesis_installed=$(oc get syndesis -o name | wc -l)
+    local force=$(hasflag --force)
     if [ $syndesis_installed -gt 0 ]; then
-        oc delete $(oc get syndesis -o name)
-    fi
-
-    oc create -f $(appdir install/operator/deploy)/syndesis.yml
-}
-
-create_oauthclient() {
-    local tag=${1:-}
-    local use_local_resource=${2:-}
-
-    create_openshift_resource \
-        "install/support/serviceaccount-as-oauthclient-restricted.yml" \
-        "$tag" \
-        "$use_local_resource"
-}
-
-create_and_apply_template() {
-    local route=$1
-    local console=${2:-}
-    local template=${3:-syndesis}
-    local tag="$(readopt --tag)"
-    local use_local_resource="$(hasflag --local)"
-    local test_support="$(hasflag --test-support)"
-
-    if [ -z "$route" ]; then
-        echo "No route given"
-        exit 1
-    fi
-
-    create_openshift_resource \
-        "install/${template}.yml" \
-        "$tag" \
-        "$use_local_resource"
-
-    local template_name=$(get_template_name $template $tag)
-    # Use '-restricted' template for tag <= 1.2
-    if [ -n "$tag" ] && [[ $tag =~ 1\.[12] ]]; then
-        template_name="${template_name}-restricted"
-    fi
-
-    local optional_args=""
-    if [ -n "$(readopt --memory-server)" ]; then
-      optional_args="$optional_args -p SERVER_MEMORY_LIMIT=$(readopt --memory-server)"
-    fi
-    if [ -n "$(readopt --memory-meta)" ]; then
-      optional_args="$optional_args -p META_MEMORY_LIMIT=$(readopt --memory-meta)"
-    fi
-    if [ $(hasflag --test-support) ]; then
-      optional_args="$optional_args -p TEST_SUPPORT_ENABLED=true"
-    fi
-
-    oc new-app --template=${template_name} \
-      -p ROUTE_HOSTNAME="${route}" \
-      -p OPENSHIFT_CONSOLE_URL="${console}" \
-      -p OPENSHIFT_MASTER="$(oc whoami --show-server)" \
-      -p OPENSHIFT_PROJECT="$(oc project -q)" \
-      -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client) \
-      $optional_args
-}
-
-# Try first a template with the tag as combination
-get_template_name() {
-    local template=$1
-    local tag=${2:-}
-    if [ -n "$tag" ]; then
-        local candidate="$template-$tag"
-        $(oc get template $candidate >/dev/null 2>&1)
-        if [ $? -eq 0 ]; then
-          echo $candidate
-          return
+        if [ -n "${force}" ]; then
+            oc delete $(oc get syndesis -o name)
         fi
     fi
 
+    local syndesis=$(cat <<EOT
+apiVersion: "syndesis.io/v1alpha1"
+kind: "Syndesis"
+metadata:
+  name: "app"
+spec:
+EOT
+)
+    local extra=""
+    if [ -n "$console" ]; then
+        extra=$(cat <<EOT
 
-    echo $template
+  openShiftConsoleUrl: $console
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+    if [ -n "$route" ]; then
+        extra=$(cat <<EOT
+
+  routeHostname: $route
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+    if [ $(hasflag --test-support) ]; then
+        extra=$(cat <<EOT
+
+  testSupport: true
+EOT
+)
+
+        syndesis="${syndesis}${extra}"
+    fi
+
+    local memory_server=$(readopt --memory-server)
+    local memory_meta=$(readopt --memory-meta)
+    if [ -n "$memory_server" ] || [ -n "$memory_meta" ]; then
+        extra=$(cat <<EOT
+
+  components:
+EOT
+)
+    fi
+    if [ -n "$memory_server" ]; then
+        extra=$(cat <<EOT
+
+    server:
+      resources:
+        limits:
+          memory: $memory_server
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+    if [ -n "$memory_meta" ]; then
+        extra=$(cat <<EOT
+
+    meta:
+      resources:
+        limits:
+          memory: $memory_meta
+EOT
+)
+        syndesis="${syndesis}${extra}"
+    fi
+
+    echo "$syndesis" | cat | oc create -f -
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Error while creating resource"
+        echo "$syndesis"
+        return
+    fi
+}
+
+# Fix up some extra permissions required for a regular minishift user
+# Must be run when root
+fix_permissions_for_operator() {
+    local user="$1"
+    if [ -z "$user" ]; then
+        echo "ERROR: No user provided to fix permissions for"
+        return
+    fi
+    local extra_role_installed=$(oc get role -o name | grep syndesis-extra-permissions)
+    if [ -z "$extra_role_installed" ]; then
+        oc create -f - <<EOT
+---
+kind: Role
+apiVersion: rbac.authorization.k8s.io/v1beta1
+metadata:
+  name: syndesis-extra-permissions
+  labels:
+    app: syndesis
+    syndesis.io/app: syndesis
+    syndesis.io/type: operator
+    syndesis.io/component: syndesis-operator
+rules:
+- apiGroups:
+  - syndesis.io
+  resources:
+  - syndesises
+  - syndesises/finalizers
+  verbs: [ get, list, create, update, delete, deletecollection, watch ]
+- apiGroups:
+  - route.openshift.io
+  resources:
+  - routes/custom-host
+  verbs: [ get, list, create, update, delete, deletecollection, watch ]
+---
+
+EOT
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Can not install role 'syndesis-extra-permissions'"
+            return
+        fi
+    fi
+
+    oc policy add-role-to-user --role-namespace="$(oc project -q)" syndesis-extra-permissions $user
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Can not add role 'syndesis-extra-permssionns' to user $user"
+        return
+    fi
 }
 
 create_openshift_resource() {
     local resource=${1:-}
-    local tag=${2:-}
-    local use_local_resource=${3:-}
+    local tag="$(readopt --tag)"
+    local use_local_resource="$(hasflag --local)"
 
-
-    # Adapt to old names if tag is smaller than 1.3. Remove this when going to
-    # GA
-    if [ -n "$tag" ]; then
-        if [[ $tag =~ 1\.[12] ]] && [[ ! $resource =~ restricted ]]; then
-          local base=$(basename $resource .yml)
-          local dir=$(dirname $resource)
-          resource="$dir/../app/deploy/${base}-restricted.yml"
-        fi
-    fi
 
     if [ -n "$use_local_resource" ]; then
         if [ -n "$tag" ]; then
@@ -337,31 +373,6 @@ patch_imagestreams_for_initial_image() {
         local remove_import_policy='{"op": "remove", "path": "/spec/tags/0/importPolicy"}'
         oc patch is $is --type json -p="[$replace_kind, $replace_name, $remove_import_policy]"
     done
-}
-
-guess_route() {
-    local project=${1:-}
-    if [ -z "${project}" ]; then
-        project=$(oc project -q)
-    fi
-    local log=$(oc create service clusterip smokeservice --tcp=4343 2>&1 && \
-                oc create route edge --service=smokeservice 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot create pivot route\n$log"
-        exit 1
-    fi
-    local domain=$(oc get route smokeservice -o template  --template='{{.spec.host}}' 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot extract route: $domain"
-        exit 1
-    fi
-    log=$(oc delete service smokeservice 2>&1 && \
-          oc delete route smokeservice 2>&1)
-    if [ $? != 0 ]; then
-        echo "ERROR: Cannot delete pivot route\n$log"
-        exit 1
-    fi
-    echo "${project}.${domain#*.}"
 }
 
 pod() {
