chore(install): Added better error handling and split up admin setup

diff --git a/tools/bin/commands/util/openshift_funcs b/tools/bin/commands/util/openshift_funcs
--- a/tools/bin/commands/util/openshift_funcs
+++ b/tools/bin/commands/util/openshift_funcs
@@ -78,6 +78,7 @@ recreate_project() {
     oc project "${project}"
 }
 
+
 # Install the Syndesis custom resource definition
 install_syndesis_crd() {
     set +e
@@ -85,13 +86,14 @@ install_syndesis_crd() {
     local err=$?
     set -e
     if [ $err -ne 0 ]; then
-        echo "ERROR: Cannot install CRD 'Syndesis'. You have to have cluster admin permission to do this"
+        echo "ERROR: Cannot install CRD 'Syndesis'. You have to be a cluster admin to do this."
         return
     fi
 
     local crd_installed=$(oc get crd -o name | grep syndesises.syndesis.io)
     if [ -z "$crd_installed" ]; then
-        create_openshift_resource "install/operator/deploy/syndesis-crd.yml"
+        local result=$(create_openshift_resource "install/operator/deploy/syndesis-crd.yml")
+        check_error $result
     fi
 }
 
@@ -99,18 +101,61 @@ install_syndesis_crd() {
 deploy_syndesis_operator() {
     local operator_installed=$(oc get dc -o name | grep syndesis-operator)
     if [ -n "$operator_installed" ]; then
-        oc delete dc syndesis-operator
-        wait_for_deployments 0 syndesis-operator
+        local result=$(delete_openshift_resource "install/operator/deploy/syndesis-operator.yml")
+        check_error $result
+        wait_for_deployments 0 syndesis-operator >/dev/null 2>&1
     fi
 
-    create_openshift_resource "install/operator/deploy/syndesis-operator.yml"
+    local result=$(create_openshift_resource "install/operator/deploy/syndesis-operator.yml")
+    check_error $result
     if [ $(hasflag --local) ]; then
         # we need to include the `syndesis-template.yml` akka `syndesis.yml` in
         # the operator image, this adds a ConfigMap that we mount into the
         # operator container
         oc delete configmap syndesis-template >/dev/null 2>&1
-        oc create configmap syndesis-template --from-file=template=$(appdir)/../install/syndesis.yml
-        oc patch deploymentconfig syndesis-operator -p '{"spec":{"template":{"spec":{"containers":[{"name":"syndesis-operator","command":["syndesis-operator","-template","/conf/syndesis-template.yml"],"volumeMounts":[{"mountPath":"/conf","name":"syndesis-template-config"}]}],"volumes":[{"configMap":{"name":"syndesis-template","items":[{"key":"template","path":"syndesis-template.yml"}]},"name":"syndesis-template-config"}]}}}}'
+        oc create configmap syndesis-template --from-file=template=$(appdir "install/syndesis.yml")
+        local patch=$(cat - <<EOT
+        {
+          "spec": {
+            "template": {
+              "spec": {
+                "containers": [
+                  {
+                    "name": "syndesis-operator",
+                    "command": [
+                      "syndesis-operator",
+                      "-template",
+                      "/conf/syndesis-template.yml"
+                    ],
+                    "volumeMounts": [
+                      {
+                        "mountPath": "/conf",
+                        "name": "syndesis-template-config"
+                      }
+                    ]
+                  }
+                ],
+                "volumes": [
+                  {
+                    "configMap": {
+                      "name": "syndesis-template",
+                      "items": [
+                        {
+                          "key": "template",
+                          "path": "syndesis-template.yml"
+                        }
+                      ]
+                    },
+                    "name": "syndesis-template-config"
+                  }
+                ]
+              }
+            }
+          }
+        }
+EOT
+)
+        oc patch deploymentconfig syndesis-operator -p "$patch"
     fi
 }
 
@@ -211,8 +256,9 @@ add_user_permissions_for_operator() {
         return
     fi
     local extra_role_installed=$(oc get role -o name | grep syndesis-extra-permissions)
+    set +e
     if [ -z "$extra_role_installed" ]; then
-        oc create -f - <<EOT
+        oc create -f - >/dev/null 2>&1 <<EOT
 ---
 kind: Role
 apiVersion: rbac.authorization.k8s.io/v1beta1
@@ -239,36 +285,59 @@ rules:
 
 EOT
         if [ $? -ne 0 ]; then
-            echo "ERROR: Can not install role 'syndesis-extra-permissions'"
-            return
+            echo "ERROR: Can not install role 'syndesis-extra-permissions'. Are you running as cluster-admin ?"
+            exit 1
         fi
     fi
 
     oc policy add-role-to-user --role-namespace="$(oc project -q)" syndesis-extra-permissions $user
     if [ $? -ne 0 ]; then
-        echo "ERROR: Can not add role 'syndesis-extra-permssionns' to user $user"
-        return
+        echo "ERROR: Can not add role 'syndesis-extra-permssionns' to user $user. Does the user exist ?"
+        exit 1
     fi
+    set -e
 }
 
 create_openshift_resource() {
-    local resource=${1:-}
+    create_or_delete_openshift_resource "create" "${1:-}"
+}
+
+delete_openshift_resource() {
+    create_or_delete_openshift_resource "delete --ignore-not-found" "${1:-}"
+}
+
+create_or_delete_openshift_resource() {
+    local what=${1}
+    local resource=${2:-}
     local tag="$(readopt --tag)"
     local use_local_resource="$(hasflag --local)"
 
+    local result
 
+    set +e
     if [ -n "$use_local_resource" ]; then
         if [ -n "$tag" ]; then
             pushd $(appdir) >/dev/null
             git fetch --tags
-            git show $tag:${resource} | oc create -f -
+            result=$(git show $tag:${resource} | oc $what -f - >$ERROR_FILE 2>&1)
+            if [ $? -ne 0 ]; then
+                echo "ERROR: Cannot create $resource (tag: $tag)"
+            fi
             popd >/dev/null
         else
-            oc create -f $(appdir)/../$resource
+            result=$(oc $what -f $(appdir)/../$resource >$ERROR_FILE 2>&1)
+            if [ $? -ne 0 ]; then
+                echo "ERROR: Cannot create local $(appdir)/../$resource"
+            fi
         fi
     else
-        oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/${tag:-master}/${resource}
+        local url="https://raw.githubusercontent.com/syndesisio/syndesis/${tag:-master}/${resource}"
+        result=$(oc $what -f $url >$ERROR_FILE 2>&1)
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Cannot create remote resource $url"
+        fi
     fi
+    set -e
 }
 
 scale_deployments() {
@@ -303,7 +372,8 @@ wait_for_deployments() {
 get_replicas() {
   local dc=${1}
   local hasDc=$(oc get dc -o name | grep $dc)
-  if [ -z $hasDc ]; then
+  if [ -z "$hasDc" ]; then
+      echo "0"
       return
   fi
   oc get dc $dc -o jsonpath="{.status.availableReplicas}"
