chore: run operator tests from `syndesis` tool

diff --git a/tools/bin/commands/util/operator_funcs b/tools/bin/commands/util/operator_funcs
--- a/tools/bin/commands/util/operator_funcs
+++ b/tools/bin/commands/util/operator_funcs
@@ -6,6 +6,23 @@ GO_BUILDER_IMAGE="syndesis/godev:1.10"
 # Name of the operator image
 OPERATOR_IMAGE="syndesis/syndesis-operator"
 
+# globs to test
+TEST_TARGETS="./cmd/... ./pkg/..."
+
+# $GOPATH volume to share between docker runs
+DOCKER_GOPATH_VOLUME=$(mktemp -d ${TMPDIR:-/tmp}/gopath.XXXXX)
+
+# $XDG_CACHE_HOME ($GOCACHE) volume to share between docker runs
+DOCKER_CACHE_VOLUME=$(mktemp -d ${TMPDIR:-/tmp}/gocache.XXXXX)
+
+CLEANUP_DIRS=()
+
+cleanup() {
+  rm -rf ${CLEANUP_DIRS[@]}
+}
+
+trap cleanup EXIT
+
 dep_ensure() {
     local operator_dir=${1}
     local do_local=${2:-}
@@ -20,13 +37,16 @@ dep_ensure() {
         dep ensure -vendor-only -v
     else
         echo "Running 'dep ensure' with $GO_BUILDER_IMAGE"
-        [ -d "dep-cache" ] || mkdir dep-cache
+        required_dirs
         local extra_opts=""
         if [ -n "$as_user" ]; then
             extra_opts="$extra_opts -u $as_user"
         fi
         docker run -w /gopath/src/github.com/syndesisio/syndesis/install/operator \
+                   -u $(id -u):$(id -g) \
                    $extra_opts \
+                   -v "$DOCKER_GOPATH_VOLUME":/gopath:z \
+                   -v "$DOCKER_CACHE_VOLUME":/.cache:z \
                    -v $operator_dir/dep-cache:/gopath/pkg/dep:z \
                    -v $operator_dir:/gopath/src/github.com/syndesisio/syndesis/install/operator:z \
                    $GO_BUILDER_IMAGE \
@@ -34,11 +54,35 @@ dep_ensure() {
     fi
 }
 
-gopath_dir() {
-    if [ -z "$GOPATH" ]; then
-        echo "ERROR: You have to set your GOPATH environment variable"
+required_dirs() {
+    require_dir "$operator_dir/dep-cache"
+    require_dir "$DOCKER_CACHE_VOLUME"
+    require_dir "$DOCKER_GOPATH_VOLUME/pkg/dep"
+    require_dir "$DOCKER_GOPATH_VOLUME/src/github.com/syndesisio/syndesis/install/operator"
+
+    CLEANUP_DIRS+=($DOCKER_GOPATH_VOLUME)
+    CLEANUP_DIRS+=($DOCKER_CACHE_VOLUME)
+}
+
+require_dir() {
+    local dir=${1}
+    [ -d "$dir" ] || mkdir -p $dir
+    if [ "$(stat --format '%u:%g' $dir)" != "$(id -u)":"$(id -g)" ]; then
+        echo "ERROR: $dir is not owned by the current user"
         exit 1
     fi
+}
+
+gopath_dir() {
+    set +o nounset
+    if [ -z "$GOPATH" ]; then
+        if [ ! -d "$HOME/go" ]; then
+          echo "ERROR: You have to set your GOPATH environment variable and the $HOME/go directory doesn't exist"
+          exit 1
+        fi
+        GOPATH="$HOME/go"
+    fi
+    set -o nounset
     local dir=$GOPATH/src/github.com/syndesisio/syndesis/install/operator
     if [ ! -d "$dir" ]; then
         echo "ERROR: No directory $dir"
@@ -51,6 +95,7 @@ build_operator() {
     local do_local="${2:-}"
     local do_linux="${3:-}"
     local as_user="${4:-}"
+    local do_skip_tests="${5:-}"
 
     if [ ! -d "$operator_dir/vendor" ] || [ $(ls "$operator_dir/vendor" | wc -l) == 0 ]; then
         echo "Running dep ensure implicitely"
@@ -62,6 +107,10 @@ build_operator() {
         local dir=$(gopath_dir)
         check_error $dir
         pushd $dir >/dev/null
+        if [ ! "$do_skip_tests" ]; then
+            echo "Running tests"
+            go test $TEST_TARGETS
+        fi
         if [ "$do_linux" ] && [ $(isOSX) ]; then
             echo "Cross-compiling syndesis-operator for Linux"
             GOOS="linux" GOARCH="amd64" CGO_ENABLED=0 go build ./cmd/syndesis-operator
@@ -76,12 +125,21 @@ build_operator() {
         if [ -n "$as_user" ]; then
             extra_opts="$extra_opts -u $as_user -e XDG_CACHE_HOME=.cache"
         fi
+        local cmd="(echo Compiling syndesis-operator; go build ./cmd/syndesis-operator)"
+        if [ ! "$do_skip_tests" ]; then
+            cmd="(echo Running tests; go test $TEST_TARGETS) && $cmd"
+        fi
+        required_dirs
         docker run -w /gopath/src/github.com/syndesisio/syndesis/install/operator \
+                   -u $(id -u):$(id -g) \
                    $extra_opts \
+                   -v "$DOCKER_GOPATH_VOLUME":/gopath:z \
+                   -v "$DOCKER_CACHE_VOLUME":/.cache:z \
+                   -v $operator_dir/dep-cache:/gopath/pkg/dep:z \
                    -v $operator_dir:/gopath/src/github.com/syndesisio/syndesis/install/operator:z \
                    -e CGO_ENABLED=0 \
                    $GO_BUILDER_IMAGE \
-                   go build ./cmd/syndesis-operator
+                   sh -c "$cmd"
     fi
 }
 
